# Generated by Django 5.2.11 on 2026-02-27 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this analysis run', primary_key=True, serialize=False)),
                ('ticker', models.CharField(db_index=True, help_text='Stock ticker symbol (e.g., TSLA, AAPL)', max_length=10)),
                ('timeframe', models.CharField(default='30d', help_text='Time period for technical analysis (e.g., 30d, 90d, 1y)', max_length=10)),
                ('include_social', models.BooleanField(default=True, help_text='Whether to include social sentiment analysis')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('agent_outputs', models.TextField(blank=True, help_text='JSON array of individual agent outputs', null=True)),
                ('consensus_data', models.TextField(blank=True, help_text='JSON object containing final consensus decision', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the Celery task actually started processing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the analysis finished', null=True)),
                ('execution_time', models.IntegerField(blank=True, help_text='Total execution time in seconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is FAILED', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times this task has been retried')),
                ('llm_model', models.CharField(default='llama-3.1-70b-versatile', help_text='LLM model used for analysis', max_length=100)),
                ('news_sources_count', models.IntegerField(blank=True, help_text='Number of news sources analyzed', null=True)),
                ('price_data_points', models.IntegerField(blank=True, help_text='Number of price data points analyzed', null=True)),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'ticker'], name='agents_agen_created_05a917_idx'), models.Index(fields=['status', 'created_at'], name='agents_agen_status_27cafa_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('actual_outcome', models.CharField(blank=True, help_text='What actually happened (for backtesting accuracy)', max_length=50, null=True)),
                ('actual_price_change', models.FloatField(blank=True, help_text='Actual price change % after 7/30 days', null=True)),
                ('original_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'Analysis Archive',
                'verbose_name_plural': 'Analysis Archives',
                'ordering': ['-archived_at'],
            },
        ),
    ]
